### ISSUE TITLE
Name to be used in credits of Racket 7.5?

### ISSUE THREAD

**Issue by jbclements** [therockmandolinist/dotfiles#1]
Apologies for using a GitHub issue for this, it's the easiest way I know of to reach people... I'm wondering if you have a preference for how your name appears in the contributors list for Racket 7.5. Do you prefer "dieggsy" or "Diego Mundo" or something else entirely?

Many thanks,

John Clements (Racket Release Manager)

**Comment by dieggsy** [comment]
Oh, I thought I'd given the appropriate info for this, sorry. "Diego A. Mundo" would be fine, if that works

**Comment by jbclements** [comment]
Yes, this is unrelated to the whole licensing thing, it’s just that we want to list you as someone that contributed code to this release. See e.g. the credits at the bottom of 

https://blog.racket-lang.org/2019/08/racket-v7-4.html

Anyhow, I”ll put “Diego A. Mundo” in there.

Thanks for your contributions!

Best,

John Clements
